### ISSUE TITLE
make commitmentAmount a percentage

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/liqbot#25]
```yaml
  - name: mybot
    location: n06.testnet.vega.xyz:3002
    marketID: 076BB86A5AA41E3E  # BTC/USD
    strategy: normal
    strategyDetails:
      posManagementFraction: 0.25
      stakeFraction: 0.1
      ordersFraction: 0.1
      commitmentAmount: 10000000000
```

Make `commitmentAmount` a percentage/fraction, so bots can automatically adjust their commitment amount depending on how much collateral they have.
